### ISSUE TITLE
Feedback welcome: Headed vs NonEmptyList

### ISSUE THREAD

**Issue by albertpastrana** [albertpastrana/uscala#11]
I've chosen `Headed` over `NonEmptyList` for some reasons:
- it's too long :stuck_out_tongue:
- it's not actually a list
- it can be confusing for people that may think it's exactly the same `NonEmptyList` available in cats/scalaz

On the other hand, there is a VERY GOOD reason to name it `NonEmptyList`: it’s the usual name used for that construct and people would be more likely to recognise what it does

I'll leave it as `Headed` for now, but I'm happy to change it to `NonEmptyList` (or other) if anybody feels strongly about it.

**Comment by nathankleyn** [comment]
I think `Headed` is okay so long it isn't `Traversable`. I am also however thinking that extending `Traversable` and implementing `forEach` could make this object much more useful anyway (then you get `map` et al without an intermediate method).

Perhaps given that, the naming could change to be `NonEmptySeq` / `NonEmptyVec` / `NonEmptyList` or something and we implement `Traversable`?

**Comment by nathankleyn** [comment]
Closing as we've shipped `headed` now and there's been no other comments here. 👍
