### ISSUE TITLE
Does Retry with maxRetries > 1 work?

### ISSUE THREAD

**Issue by dalegaspi** [albertpastrana/uscala#12]
OK this is perhaps it's my misunderstanding of how `Retry.retry()` works or it could be just i'm an overall village idiot, but for me it doesn't retry `x` times on failure if i set `maxRetries` to `x` (where `x > 1`).  I looked at the code and it does this:

```scala
 def retry[T](maxRetries: Option[Int],
               interval: Duration = DefaultInterval,
               backoff: Backoff = exponentialBackoff,
               failAction: Throwable => Unit = doNothing)
              (f: => Try[T]): Try[T] = {
    @tailrec
    def loop(retry: Int): Try[T] = f match {
      case s @ Success(_) => s
      case Failure(e) if maxRetries.forall(_ < retry) =>
        failAction(e)
        sleep(backoff(retry, interval))
        loop(retry)
      case fail => fail
    }
    loop(1)
  }
```

i'm not entirely sure how this even works when there is no increment/decrement on the param passed to `loop()`

so i changed it to:

```scala
 def retry[T](maxRetries: Option[Int],
               interval: Duration = DefaultInterval,
               backoff: Backoff = exponentialBackoff,
               failAction: Throwable => Unit = doNothing)
              (f: => Try[T]): Try[T] = {
    @tailrec
    def loop(retry: Int): Try[T] = f match {
      case s @ Success(_) => s
      case Failure(e) if maxRetries.forall(_ > retry) => // condition changed here
        failAction(e)
        sleep(backoff(retry, interval))
        loop(retry + 1) // increment here
      case fail => fail
    }
    loop(1)
  }
```

The test cases are still passing, and the code works the way _i expect it to_: retry `maxRetries` times as long as `f` is a `Failure`.

Again, I may be misunderstanding things...kindly advise.   thanks.

**Comment by albertpastrana** [comment]
Hi @dalegaspi, thanks a lot for the bug report!

This was indeed a bug, both in the code and in the test 🤦‍♂️ 

I've fixed the test and then the code, so it should be working as expected.

Right now I'm already generating `v0.9.4` with this fix in it. Should be available shortly.

Thanks again :)

**Comment by albertpastrana** [comment]
`v0.9.4` has been published https://bintray.com/albertpastrana/maven/uscala-retry/0.9.4

I'll close this issue. Feel free to open it if you see any problem :-)
