### ISSUE TITLE
Scala 2.12 on jcenter

### ISSUE THREAD

**Issue by DanielFallon** [albertpastrana/uscala#7]
uscala packages don't appear to resolve for jcenter for scala 2.12 

see generated url:
https://jcenter.bintray.com/org/uscala/uscala-result_2.12/0.5.1/

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.uscala#uscala-result_2.12;0.5.1: not found
[warn]  :: org.uscala#uscala-result-async_2.12;0.5.1: not found
[warn]  :: org.uscala#uscala-result-specs2_2.12;0.5.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

it works if I add `resolvers += Resolver.bintrayRepo("albertpastrana", "maven")` to my build, but that's inelegant considering that the build was promoted. I've never published to bintray, so I'm not sure what caused the old version to be published and the new version not, any thoughts?

**Comment by albertpastrana** [comment]
Hi @DanielFallon, sorry for the late answer. Luckily @nathankleyn has fixed the cross version build and I'll try to publish a new version asap.

**Comment by albertpastrana** [comment]
Hi again @DanielFallon,

After trying to publish it again it still didn't work so I contacted JCenter. They've answered super fast with the following
> We have managed to resolve the issue you were experiencing. 
> The issue occurred due to a bad link to JCenter. We have relinked the package and this resolved the issue. 

You can see it now in jcenter:
https://jcenter.bintray.com/org/uscala/uscala-result_2.12/0.6.1/

I've asked them to do the same for the rest of the packages, hopefully they will be published soon enough.

**Comment by albertpastrana** [comment]
The rest of the µ-libraries have been correctly published to jcenter.
I've tested in in a local project and it worked, so I'm closing this issue. Please, reopen it if you have any further problem.
